Review
Programistic/karty-podskazhut pull request #1
Opened 2023-11-27 14:11 UTC by Programistic

2023-11-27 16:36 UTC, Avaakum requested changes
Развернуть общий комментарий ⬇︎

Доброго времени суток. У вас получилась хорошая работа!

_Что понравилось:_

- работают темы
- отличная структура файлов проекта
- Хорошая семантика
- Хорошие стили 
- Отзывчивая верстка
- Похоже на макет на брейк-поинтах


_Что необходимо исправить:_

- Все комментарии, кроме комментариев «Можно лучше» и «Отлично»



- https://disk.yandex.ru/i/B4cfnQ9bedRdkQ  Маркеры списка должны находится по центру  напротив элемента списка, а не по верхней строке. Для этого нужно опустить вниз буллит на  50% элемента списка , например с помощью  inset-block-start и затем поднять его на половину собственной высоты(7.5px) с помощью margin-block-start. 



- При ширине экрана 360px _не совпадает с макетом_:
   - https://disk.yandex.ru/i/VaHlWUXCbbHSJA высота строки




_Что можно улучшить:_

- Все комментарии с пометкой "Можно лучше"
- Для всех функций ` var() ` в CSS нужно задать резервные значения,  на случай если доступ к кастомному свойству по имени будет невозможен. 
- больше использовать vi вместо vw


Желаю успеха!

2023-11-27 16:36 UTC, Avaakum commented on index.html
> +          И кстати, сейчас необязательно охотиться за редкими физическими колодами Oblique Strategies — тем более, что их моментально разбирают фанаты Ино. Есть довольно симпатичные <a class="content
Между тегов ссылки должно быть "для iOS"

2023-11-27 16:36 UTC, Avaakum commented on index.html
> +          И кстати, сейчас необязательно охотиться за редкими физическими колодами Oblique Strategies — тем более, что их моментально разбирают фанаты Ино. Есть довольно симпатичные <a class="content
Между тегов ссылки должно быть "для iOS"

2023-11-27 16:36 UTC, Avaakum commented on styles/style.css
> +  max-width: 1440px;
Для этой страницы не должно быть максимального ограничения ширины контент, она должна тянуться на любую ширину экрана.

2023-11-27 16:36 UTC, Avaakum commented on index.html
> +        <div class="header__logo">
Логотип должен быть ссылкой без атрибута href(что бы по ссылке не было перехода)  для улучшения семантики страницы. А так же, что бы при навигации с клавиатуры этот элемент не получал видимый фокус.

2023-11-27 16:36 UTC, Avaakum commented on index.html
> +          И кстати, сейчас необязательно охотиться за редкими физическими колодами Oblique Strategies — тем более, что их моментально разбирают фанаты Ино. Есть довольно симпатичные <a class="content
---

**Отлично:**

Корректно заданы ссылки

2023-11-27 16:36 UTC, Avaakum commented on index.html
> +          <source srcset="./images/cards-1x.avif 1x, ./images/cards-2x.avif 2x" type="image/avif">
---

**Отлично:**

правильно заданы альтернативы для экранов с разной плотностью пикселей

2023-11-27 16:36 UTC, Avaakum commented on index.html
> +          <img class="content__picture" src="./images/cards-1x.png" srcset="./images/cards-1x.png 1x, ./images/cards-2x.png 2x" loading="lazy" alt="На картинке на столе комнатный цветок, рядом iPhone
---

**Можно лучше:**

атрибут src можно удалить

2023-11-27 16:36 UTC, Avaakum commented on index.html
> +      <figure class="content__figure">
---

**Отлично:**

Отличная семантика

2023-11-27 16:36 UTC, Avaakum commented on styles/style.css
> +  font: 600 30px/.9 'STIX Two Text', serif;
---

**Отлично:**

Классное сокращённое св-во

2023-11-28 12:14 UTC, Programistic commented on index.html
> +          И кстати, сейчас необязательно охотиться за редкими физическими колодами Oblique Strategies — тем более, что их моментально разбирают фанаты Ино. Есть довольно симпатичные <a class="content
Исправлено

2023-11-28 12:23 UTC, Programistic commented on styles/style.css
> +  max-width: 1440px;
Исправлено

2023-11-28 12:54 UTC, Programistic commented on index.html
> +        <div class="header__logo">
Исправлено

2023-11-28 12:57 UTC, Programistic commented on index.html
> +          <img class="content__picture" src="./images/cards-1x.png" srcset="./images/cards-1x.png 1x, ./images/cards-2x.png 2x" loading="lazy" alt="На картинке на столе комнатный цветок, рядом iPhone
Исправлено

2023-12-02 13:54 UTC, Avaakum approved these changes
Развернуть общий комментарий ⬇︎

Здравствуйте! Рад вам сообщить, что ваша работа принята. Сейчас страничка выглядит прекрасно, всё работает отлично. Отличная семантика и структура. Желаю вам удачи в следующих спринтах и проектах! 


Ссылки:

- Можно использовать неразрывные пробелы для того чтобы текст не переносился в неожиданных местах. Неразрывные пробелы заменяют обычные, если нужно чтобы какая-то фраза не переносилась, например не нужно чтобы "на собаках" раскидывалось по разным строчкам при некоторых ширинах экранов, тогда `«на&nbsp;собаках»`. Но если страница с адаптацией, то всегда стоит проверять как текст с пробелами выглядит на всех ширинах.
- Про альтернативный текст для картинок https://habr.com/ru/post/341810/
- [Ссылка про подгрузку шрифтов](https://only-to-top.ru/blog/tools/2019-03-13-nastrojte-pokaz-vsego-teksta-vo-vremya-zagruzki-veb-shriftov.html) 
- Для более точной корректировки размеров текстов и расстояний между элементами можно воспользоваться [расширением PixelPerfect](https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi) для Chrome 



Несколько  ссылок на материал по теме нативных CSS переменных от авторов практикума:

- [1 часть](https://tproger.ru/articles/custom-properties-in-css-part-1/)

- [2 часть](https://tproger.ru/articles/custom-properties-in-css-part-2/)

- [3 часть](https://tproger.ru/articles/custom-properties-in-css-part-3/)

2023-12-02 14:42 UTC, merged